name: Flying_Islands
main: com.ftwinston.KillerMinecraft.Modules.FlyingIslands.Plugin
depend: [Killer_Minecraft]
version: 1
load: STARTUP
description: A world generator for Killer Minecraft
author: FTWinston